#!/usr/bin/env bash
set -euo pipefail

WORKSPACE="/root/.openclaw/workspace"
SKILL_DIR="$WORKSPACE/skills/notion-workspace"
CREDENTIALS_DIR="${HOME}/.openclaw/credentials"
ENV_FILE="$CREDENTIALS_DIR/notion-workspace.env"

write_embedded_file() {
  local dest="$1"
  local b64="$2"
  mkdir -p "$(dirname "$dest")"
  printf %s "$b64" | base64 -d > "$dest"
}

mkdir -p "$SKILL_DIR"
mkdir -p "$CREDENTIALS_DIR"

echo "Installing Notion Workspace skill into:"
echo "  $SKILL_DIR"
echo ""
write_embedded_file "$SKILL_DIR/SKILL.md" "LS0tCm5hbWU6IG5vdGlvbi13b3Jrc3BhY2UKZGVzY3JpcHRpb246IEFjY2VzcyBhIGNvbm5lY3RlZCBOb3Rpb24gd29ya3NwYWNlIHRocm91Z2ggdGhlIE5vdGlvbiBBUEkgZm9yIHNlYXJjaCwgcGFnZSBsb29rdXAsIHNpbXBsZSBkYXRhYmFzZSBxdWVyaWVzLCBhbmQgYXBwZW5kaW5nIGJsb2Nrcy4gVXNlIHdoZW4gdGhlIHVzZXIgd2FudHMgdG8gcmVhZCBmcm9tIG9yIHdyaXRlIHRvIE5vdGlvbiwgaW5zcGVjdCB3b3Jrc3BhY2UgYWNjZXNzLCBmaW5kIGEgcGFnZS9kYXRhYmFzZSwgb3IgdXBkYXRlIGFuIGV4aXN0aW5nIE5vdGlvbiBwYWdlIGZyb20gdGhpcyBPcGVuQ2xhdyB3b3Jrc3BhY2UuCi0tLQoKIyBOb3Rpb24gV29ya3NwYWNlCgpVc2UgdGhlIGJ1bmRsZWQgc2NyaXB0IGZvciBkZXRlcm1pbmlzdGljIE5vdGlvbiBBUEkgYWNjZXNzLgoKIyMgUXVpY2sgc3RhcnQKCi0gVXNlIGBzY3JpcHRzL25vdGlvbl9hcGkucHkgbWVgIHRvIHZlcmlmeSB0aGUgaW50ZWdyYXRpb24gdG9rZW4gd29ya3MuCi0gVXNlIGBzY3JpcHRzL25vdGlvbl9hcGkucHkgc2VhcmNoICJxdWVyeSJgIHRvIGZpbmQgcGFnZXMgYW5kIGRhdGFiYXNlcyB0aGUgaW50ZWdyYXRpb24gY2FuIGFjY2Vzcy4KLSBVc2UgYHNjcmlwdHMvbm90aW9uX2FwaS5weSBwYWdlIDxwYWdlLWlkPmAgdG8gaW5zcGVjdCBhIHBhZ2UuCi0gVXNlIGBzY3JpcHRzL25vdGlvbl9hcGkucHkgZGF0YWJhc2UtcXVlcnkgPGRhdGFiYXNlLWlkPiAnWy4uLl0nYCBvbmx5IHdoZW4geW91IGFscmVhZHkga25vdyB0aGUgZGF0YWJhc2UgaWQgYW5kIG5lZWQgc3RydWN0dXJlZCByZXN1bHRzLgotIFVzZSBgc2NyaXB0cy9ub3Rpb25fYXBpLnB5IGFwcGVuZC1ibG9ja3MgPGJsb2NrLWlkPiAnPGpzb24+J2AgZm9yIHNtYWxsLCBleHBsaWNpdCBjb250ZW50IGFwcGVuZHMuCgpSdW4gY29tbWFuZHMgZnJvbSB0aGlzIHNraWxsIGRpcmVjdG9yeSBvciB1c2UgdGhlIGZ1bGwgc2NyaXB0IHBhdGguCgojIyBDcmVkZW50aWFsIGhhbmRsaW5nCgotIEV4cGVjdCB0aGUgdG9rZW4gaW4gYH4vLm9wZW5jbGF3L2NyZWRlbnRpYWxzL25vdGlvbi13b3Jrc3BhY2UuZW52YCBhcyBgTk9USU9OX0FQSV9LRVk9Li4uYC4KLSBEbyBub3QgcHJpbnQgdGhlIHRva2VuIGJhY2sgdG8gdGhlIHVzZXIuCi0gSWYgdGhlIHVzZXIgcGFzdGVkIHRoZSB0b2tlbiBpbiBjaGF0LCB0cmVhdCBpdCBhcyBleHBvc2VkIGFuZCByZWNvbW1lbmQgcm90YXRpbmcgaXQgYWZ0ZXIgc2V0dXAuCgojIyBXb3JrZmxvdwoKMS4gVmVyaWZ5IGFjY2VzcyB3aXRoIGBtZWAuCjIuIERpc2NvdmVyIHRhcmdldHMgd2l0aCBgc2VhcmNoYC4KMy4gUmVhZCBiZWZvcmUgd3JpdGluZy4KNC4gRm9yIHdyaXRlcywga2VlcCBvcGVyYXRpb25zIHNtYWxsIGFuZCBleHBsaWNpdC4KNS4gU2hvdyB0aGUgdXNlciB3aGF0IHN1Y2NlZWRlZCBhbmQgd2hhdCBzdGlsbCBuZWVkcyBOb3Rpb24tc2lkZSBzaGFyaW5nIHBlcm1pc3Npb25zLCBpZiBhbnkuCgojIyBXcml0aW5nIGd1aWRhbmNlCgotIFByZWZlciBhcHBlbmRpbmcgYmxvY2tzIHRvIGFuIGV4aXN0aW5nIHBhZ2Ugb3ZlciBsYXJnZSBkZXN0cnVjdGl2ZSByZXdyaXRlcy4KLSBJZiBhIHBhZ2Ugb3IgZGF0YWJhc2UgaXMgbWlzc2luZyBmcm9tIHNlYXJjaCByZXN1bHRzLCB0aGUgaW50ZWdyYXRpb24gdXN1YWxseSBoYXMgbm90IGJlZW4gc2hhcmVkIHRvIHRoYXQgcmVzb3VyY2UgaW4gTm90aW9uIHlldC4KLSBXaGVuIHRoZSB1c2VyIGFza3MgZm9yIGJyb2FkIHN5bmMgYmVoYXZpb3IsIGV4cGxhaW4gdGhhdCB0aGlzIHNraWxsIGN1cnJlbnRseSBwcm92aWRlcyBkaXJlY3QgQVBJIG9wZXJhdGlvbnMsIG5vdCBhIGZ1bGwgYmFja2dyb3VuZCBzeW5jIGVuZ2luZS4K"
write_embedded_file "$SKILL_DIR/README.md" "IyBOb3Rpb24gV29ya3NwYWNlIFNraWxsCgpUaGlzIGFkZHMgc2ltcGxlIE5vdGlvbiBhY2Nlc3MgdG8gT3BlbkNsYXcuCgojIyBRdWljayBzdGFydAoKIyMjIFN0ZXAgMTogUHV0IHRoZXNlIGZpbGVzIHNvbWV3aGVyZSBvbiB0aGUgc2VydmVyCgpCZXN0IG9wdGlvbjoKLSBgaW5zdGFsbC1ub3Rpb24td29ya3NwYWNlLnNoYAotIGAubm90aW9uLXdvcmtzcGFjZS1idW5kbGUvYAoKQWxzbyBzdXBwb3J0ZWQ6Ci0gYGluc3RhbGwtbm90aW9uLXdvcmtzcGFjZS5zaGAKLSBgbm90aW9uLXdvcmtzcGFjZS1kcm9waW4taW5zdGFsbGVyLnRhci5nemAKCklmIHRoZSBidW5kbGUgZm9sZGVyIGlzIG1pc3NpbmcsIHRoZSBpbnN0YWxsZXIgd2lsbCB0cnkgdG8gZXh0cmFjdCBpdCBmcm9tIHRoZSB0YXIuZ3ogYXV0b21hdGljYWxseS4KCiMjIyBTdGVwIDI6IFJ1biB0aGUgaW5zdGFsbGVyCgpgYGBiYXNoCmJhc2ggL3BhdGgvdG8vaW5zdGFsbC1ub3Rpb24td29ya3NwYWNlLnNoCmBgYAoKIyMjIFN0ZXAgMzogUGFzdGUgeW91ciBOb3Rpb24gc2VjcmV0IGtleQoKVGhlIGluc3RhbGxlciB3aWxsIGFzayBmb3IgeW91ciBOb3Rpb24gaW50ZWdyYXRpb24gc2VjcmV0IGFuZCBzYXZlIGl0IGZvciB5b3UuCgpZb3UgY2FuIHJ1biBpdCBmcm9tIGFueXdoZXJlLiBJdCB0cmllcyB0byBhdXRvLWRldGVjdCB0aGUgT3BlbkNsYXcgd29ya3NwYWNlIGFuZCB0aGUgYnVuZGxlIGxvY2F0aW9uIGZvciB5b3UuCgojIyMgU3RlcCA0OiBDb3B5IHRoZSBnZW5lcmF0ZWQgYWdlbnQgcHJvbXB0CgpBZnRlciBzZXR1cCwgdGhlIGluc3RhbGxlciBwcmludHMgYSByZWFkeS10by11c2UgcHJvbXB0IHRlbGxpbmcgeW91ciBPcGVuQ2xhdyBhZ2VudDoKLSB3aGVyZSB0aGUgTm90aW9uIHNraWxsIHdhcyBpbnN0YWxsZWQKLSB3aGVyZSB0aGUgY3JlZGVudGlhbHMgd2VyZSBzdG9yZWQKLSB0aGF0IGl0IHNob3VsZCB1c2UgdGhlIGNvbmZpZ3VyZWQgTm90aW9uIHNraWxsIGZvciBmdXR1cmUgTm90aW9uIHRhc2tzCgojIyMgU3RlcCA0OiBEb25lCgpUaGUgaW5zdGFsbGVyIHdpbGw6Ci0gaW5zdGFsbCB0aGUgc2tpbGwgaW50byBgc2tpbGxzL25vdGlvbi13b3Jrc3BhY2UvYAotIHNhdmUgeW91ciBrZXkgaW4gYH4vLm9wZW5jbGF3L2NyZWRlbnRpYWxzL25vdGlvbi13b3Jrc3BhY2UuZW52YAotIHRlc3QgdGhlIGNvbm5lY3Rpb24gYXV0b21hdGljYWxseQoKIyMgSW1wb3J0YW50OiBzaGFyZSBwYWdlcyB3aXRoIHlvdXIgaW50ZWdyYXRpb24KCklmIE5vdGlvbiBwYWdlcyBvciBkYXRhYmFzZXMgZG8gbm90IGFwcGVhciwgeW91IHVzdWFsbHkgbmVlZCB0byBzaGFyZSB0aGVtIHdpdGggeW91ciBOb3Rpb24gaW50ZWdyYXRpb24gaW5zaWRlIE5vdGlvbi4KCiMjIFRlc3QgaXQgbGF0ZXIKCmBgYGJhc2gKcHl0aG9uMyBza2lsbHMvbm90aW9uLXdvcmtzcGFjZS9zY3JpcHRzL25vdGlvbl9hcGkucHkgbWUKYGBgCgojIyBVc2VmdWwgZXhhbXBsZXMKClNlYXJjaCBOb3Rpb246CmBgYGJhc2gKcHl0aG9uMyBza2lsbHMvbm90aW9uLXdvcmtzcGFjZS9zY3JpcHRzL25vdGlvbl9hcGkucHkgc2VhcmNoICJwcm9qZWN0IG5vdGVzIgpgYGAKCk9wZW4gYSBwYWdlIGJ5IElEOgpgYGBiYXNoCnB5dGhvbjMgc2tpbGxzL25vdGlvbi13b3Jrc3BhY2Uvc2NyaXB0cy9ub3Rpb25fYXBpLnB5IHBhZ2UgPHBhZ2UtaWQ+CmBgYAoKIyMgTWFudWFsIGluc3RhbGwKCklmIHlvdSBkbyBub3Qgd2FudCB0aGUgZHJvcC1pbiBpbnN0YWxsZXIsIHlvdSBjYW4gYWxzbyBwbGFjZSB0aGUgc2tpbGwgZGlyZWN0bHkgaW46Cgpgc2tpbGxzL25vdGlvbi13b3Jrc3BhY2UvYAoKVGhlbiBydW46CgpgYGBiYXNoCmJhc2ggc2tpbGxzL25vdGlvbi13b3Jrc3BhY2UvaW5zdGFsbC5zaApgYGAK"
write_embedded_file "$SKILL_DIR/install.sh" "IyEvdXNyL2Jpbi9lbnYgYmFzaApzZXQgLWV1byBwaXBlZmFpbAoKU0NSSVBUX0RJUj0iJChjZCAiJChkaXJuYW1lICIke0JBU0hfU09VUkNFWzBdfSIpIiAmJiBwd2QpIgpDUkVERU5USUFMU19ESVI9IiR7SE9NRX0vLm9wZW5jbGF3L2NyZWRlbnRpYWxzIgpFTlZfRklMRT0iJHtDUkVERU5USUFMU19ESVJ9L25vdGlvbi13b3Jrc3BhY2UuZW52IgoKbWtkaXIgLXAgIiRDUkVERU5USUFMU19ESVIiCgplY2hvICJOb3Rpb24gV29ya3NwYWNlIHNraWxsIHNldHVwIgplY2hvICIiCmVjaG8gIlRoaXMgd2lsbCBzYXZlIHlvdXIgTm90aW9uIGludGVncmF0aW9uIHNlY3JldCB0bzoiCmVjaG8gIiAgJEVOVl9GSUxFIgplY2hvICIiCmVjaG8gIkNyZWF0ZSBhIE5vdGlvbiBpbnRlcm5hbCBpbnRlZ3JhdGlvbiBmaXJzdCwgdGhlbiBwYXN0ZSBpdHMgc2VjcmV0IGhlcmUuIgplY2hvICJZb3UgY2FuIGZpbmQgaXQgaW4gTm90aW9uIHVuZGVyIFNldHRpbmdzIC0+IENvbm5lY3Rpb25zIC0+IERldmVsb3Agb3IgTXkgaW50ZWdyYXRpb25zLiIKZWNobyAiIgoKaWYgW1sgLWYgIiRFTlZfRklMRSIgXV07IHRoZW4KICBlY2hvICJBbiBleGlzdGluZyBjb25maWcgd2FzIGZvdW5kLiIKICByZWFkIC1yIC1wICJPdmVyd3JpdGUgaXQ/IFt5L05dICIgb3ZlcndyaXRlCiAgY2FzZSAiJG92ZXJ3cml0ZSIgaW4KICAgIHl8WXx5ZXN8WUVTKSA7OwogICAgKikKICAgICAgZWNobyAiS2VlcGluZyBleGlzdGluZyBjb25maWcuIgogICAgICBleGl0IDAKICAgICAgOzsKICBlc2FjCmZpCgpyZWFkIC1yIC1zIC1wICJQYXN0ZSB5b3VyIE5vdGlvbiBzZWNyZXQga2V5OiAiIG5vdGlvbl9rZXkKZWNobyAiIgoKaWYgW1sgLXogIiRub3Rpb25fa2V5IiBdXTsgdGhlbgogIGVjaG8gIk5vIGtleSBlbnRlcmVkLiBBYm9ydGluZy4iCiAgZXhpdCAxCmZpCgpjYXQgPiAiJEVOVl9GSUxFIiA8PEVPRgpOT1RJT05fQVBJX0tFWT0kbm90aW9uX2tleQpFT0YKY2htb2QgNjAwICIkRU5WX0ZJTEUiCgplY2hvICIiCmVjaG8gIlNhdmVkIGNyZWRlbnRpYWxzLiIKZWNobyAiIgplY2hvICJWZXJpZnlpbmcgYWNjZXNzLi4uIgpweXRob24zICIkU0NSSVBUX0RJUi9zY3JpcHRzL25vdGlvbl9hcGkucHkiIG1lCgplY2hvICIiCmVjaG8gIlNldHVwIGNvbXBsZXRlLiIKZWNobyAiSWYgdmVyaWZpY2F0aW9uIGZhaWxlZCwgbWFrZSBzdXJlIHRoZSBzZWNyZXQgaXMgY29ycmVjdCBhbmQgdGhhdCB5b3VyIE5vdGlvbiBpbnRlZ3JhdGlvbiBpcyBhY3RpdmUuIn0="
write_embedded_file "$SKILL_DIR/scripts/notion_api.py" "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwppbXBvcnQganNvbgppbXBvcnQgb3MKaW1wb3J0IHN5cwpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCmltcG9ydCByZXF1ZXN0cwoKQVBJX0JBU0UgPSAiaHR0cHM6Ly9hcGkubm90aW9uLmNvbS92MSIKQVBJX1ZFUlNJT04gPSAiMjAyMi0wNi0yOCIKRU5WX0ZJTEUgPSBQYXRoLmhvbWUoKSAvICIub3BlbmNsYXciIC8gImNyZWRlbnRpYWxzIiAvICJub3Rpb24td29ya3NwYWNlLmVudiIKCgpkZWYgbG9hZF9lbnZfZmlsZShwYXRoOiBQYXRoKSAtPiBOb25lOgogICAgaWYgbm90IHBhdGguZXhpc3RzKCk6CiAgICAgICAgcmV0dXJuCiAgICBmb3IgcmF3IGluIHBhdGgucmVhZF90ZXh0KCkuc3BsaXRsaW5lcygpOgogICAgICAgIGxpbmUgPSByYXcuc3RyaXAoKQogICAgICAgIGlmIG5vdCBsaW5lIG9yIGxpbmUuc3RhcnRzd2l0aCgiIyIpIG9yICI9IiBub3QgaW4gbGluZToKICAgICAgICAgICAgY29udGludWUKICAgICAgICBrZXksIHZhbHVlID0gbGluZS5zcGxpdCgiPSIsIDEpCiAgICAgICAga2V5ID0ga2V5LnN0cmlwKCkKICAgICAgICB2YWx1ZSA9IHZhbHVlLnN0cmlwKCkuc3RyaXAoJyInKS5zdHJpcCgiJyIpCiAgICAgICAgb3MuZW52aXJvbi5zZXRkZWZhdWx0KGtleSwgdmFsdWUpCgoKZGVmIG5vdGlvbl90b2tlbigpIC0+IHN0cjoKICAgIGxvYWRfZW52X2ZpbGUoRU5WX0ZJTEUpCiAgICB0b2tlbiA9IG9zLmVudmlyb24uZ2V0KCJOT1RJT05fQVBJX0tFWSIpIG9yIG9zLmVudmlyb24uZ2V0KCJOT1RJT05fVE9LRU4iKQogICAgaWYgbm90IHRva2VuOgogICAgICAgIHByaW50KGpzb24uZHVtcHMoewogICAgICAgICAgICAib2siOiBGYWxzZSwKICAgICAgICAgICAgImVycm9yIjogZiJNaXNzaW5nIE5PVElPTl9BUElfS0VZLiBFeHBlY3RlZCBpdCBpbiBlbnYgb3Ige0VOVl9GSUxFfSIKICAgICAgICB9LCBpbmRlbnQ9MikpCiAgICAgICAgc3lzLmV4aXQoMikKICAgIHJldHVybiB0b2tlbgoKCmRlZiBoZWFkZXJzKCkgLT4gZGljdDoKICAgIHJldHVybiB7CiAgICAgICAgIkF1dGhvcml6YXRpb24iOiBmIkJlYXJlciB7bm90aW9uX3Rva2VuKCl9IiwKICAgICAgICAiTm90aW9uLVZlcnNpb24iOiBBUElfVkVSU0lPTiwKICAgICAgICAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb24iLAogICAgfQoKCmRlZiByZXF1ZXN0KG1ldGhvZDogc3RyLCBwYXRoOiBzdHIsIHBheWxvYWQ9Tm9uZSwgcGFyYW1zPU5vbmUpOgogICAgdXJsID0gZiJ7QVBJX0JBU0V9e3BhdGh9IgogICAgcmVzcCA9IHJlcXVlc3RzLnJlcXVlc3QobWV0aG9kLCB1cmwsIGhlYWRlcnM9aGVhZGVycygpLCBqc29uPXBheWxvYWQsIHBhcmFtcz1wYXJhbXMsIHRpbWVvdXQ9MzApCiAgICB0cnk6CiAgICAgICAgZGF0YSA9IHJlc3AuanNvbigpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIGRhdGEgPSB7InN0YXR1cyI6IHJlc3Auc3RhdHVzX2NvZGUsICJ0ZXh0IjogcmVzcC50ZXh0fQogICAgaWYgbm90IHJlc3Aub2s6CiAgICAgICAgcHJpbnQoanNvbi5kdW1wcyh7Im9rIjogRmFsc2UsICJzdGF0dXMiOiByZXNwLnN0YXR1c19jb2RlLCAicmVzcG9uc2UiOiBkYXRhfSwgaW5kZW50PTIpKQogICAgICAgIHN5cy5leGl0KDEpCiAgICBwcmludChqc29uLmR1bXBzKHsib2siOiBUcnVlLCAic3RhdHVzIjogcmVzcC5zdGF0dXNfY29kZSwgInJlc3BvbnNlIjogZGF0YX0sIGluZGVudD0yKSkKCgpkZWYgbWFpbigpOgogICAgaWYgbGVuKHN5cy5hcmd2KSA8IDI6CiAgICAgICAgcHJpbnQoIlVzYWdlOiBub3Rpb25fYXBpLnB5IDxtZXxzZWFyY2h8cGFnZXxkYXRhYmFzZS1xdWVyeXxhcHBlbmQtYmxvY2tzfGNyZWF0ZS1wYWdlfHBhZ2UtYmxvY2tzPiBbYXJncy4uLl0iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgc3lzLmV4aXQoMikKCiAgICBjbWQgPSBzeXMuYXJndlsxXQoKICAgIGlmIGNtZCA9PSAibWUiOgogICAgICAgIHJlcXVlc3QoIkdFVCIsICIvdXNlcnMvbWUiKQogICAgICAgIHJldHVybgoKICAgIGlmIGNtZCA9PSAic2VhcmNoIjoKICAgICAgICBxdWVyeSA9IHN5cy5hcmd2WzJdIGlmIGxlbihzeXMuYXJndikgPiAyIGVsc2UgIiIKICAgICAgICBwYXlsb2FkID0geyJxdWVyeSI6IHF1ZXJ5LCAicGFnZV9zaXplIjogMTB9CiAgICAgICAgcmVxdWVzdCgiUE9TVCIsICIvc2VhcmNoIiwgcGF5bG9hZD1wYXlsb2FkKQogICAgICAgIHJldHVybgoKICAgIGlmIGNtZCA9PSAicGFnZSI6CiAgICAgICAgaWYgbGVuKHN5cy5hcmd2KSA8IDM6CiAgICAgICAgICAgIHByaW50KCJVc2FnZTogbm90aW9uX2FwaS5weSBwYWdlIDxwYWdlLWlkPiIsIGZpbGU9c3lzLnN0ZGVycikKICAgICAgICAgICAgc3lzLmV4aXQoMikKICAgICAgICByZXF1ZXN0KCJHRVQiLCBmIi9wYWdlcy97c3lzLmFyZ3ZbMl19IikKICAgICAgICByZXR1cm4KCiAgICBpZiBjbWQgPT0gInBhZ2UtYmxvY2tzIjoKICAgICAgICBpZiBsZW4oc3lzLmFyZ3YpIDwgMzoKICAgICAgICAgICAgcHJpbnQoIlVzYWdlOiBub3Rpb25fYXBpLnB5IHBhZ2UtYmxvY2tzIDxwYWdlLWlkPiIsIGZpbGU9c3lzLnN0ZGVycikKICAgICAgICAgICAgc3lzLmV4aXQoMikKICAgICAgICByZXF1ZXN0KCJHRVQiLCBmIi9ibG9ja3Mve3N5cy5hcmd2WzJdfS9jaGlsZHJlbiIpCiAgICAgICAgcmV0dXJuCgogICAgaWYgY21kID09ICJkYXRhYmFzZS1xdWVyeSI6CiAgICAgICAgaWYgbGVuKHN5cy5hcmd2KSA8IDM6CiAgICAgICAgICAgIHByaW50KCJVc2FnZTogbm90aW9uX2FwaS5weSBkYXRhYmFzZS1xdWVyeSA8ZGF0YWJhc2UtaWQ+IFtqc29uLWZpbHRlcl0iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgICAgIHN5cy5leGl0KDIpCiAgICAgICAgcGF5bG9hZCA9IGpzb24ubG9hZHMoc3lzLmFyZ3ZbM10pIGlmIGxlbihzeXMuYXJndikgPiAzIGVsc2Uge30KICAgICAgICByZXF1ZXN0KCJQT1NUIiwgZiIvZGF0YWJhc2VzL3tzeXMuYXJndlsyXX0vcXVlcnkiLCBwYXlsb2FkPXBheWxvYWQpCiAgICAgICAgcmV0dXJuCgogICAgaWYgY21kID09ICJhcHBlbmQtYmxvY2tzIjoKICAgICAgICBpZiBsZW4oc3lzLmFyZ3YpIDwgNDoKICAgICAgICAgICAgcHJpbnQoIlVzYWdlOiBub3Rpb25fYXBpLnB5IGFwcGVuZC1ibG9ja3MgPGJsb2NrLWlkPiA8anNvbi1jaGlsZHJlbj4iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgICAgIHN5cy5leGl0KDIpCiAgICAgICAgcGF5bG9hZCA9IHsiY2hpbGRyZW4iOiBqc29uLmxvYWRzKHN5cy5hcmd2WzNdKX0KICAgICAgICByZXF1ZXN0KCJQQVRDSCIsIGYiL2Jsb2Nrcy97c3lzLmFyZ3ZbMl19L2NoaWxkcmVuIiwgcGF5bG9hZD1wYXlsb2FkKQogICAgICAgIHJldHVybgoKICAgIGlmIGNtZCA9PSAiY3JlYXRlLXBhZ2UiOgogICAgICAgIGlmIGxlbihzeXMuYXJndikgPCA0OgogICAgICAgICAgICBwcmludCgiVXNhZ2U6IG5vdGlvbl9hcGkucHkgY3JlYXRlLXBhZ2UgPHBhcmVudC1wYWdlLWlkPiA8dGl0bGU+IFtqc29uLWNoaWxkcmVuXSIsIGZpbGU9c3lzLnN0ZGVycikKICAgICAgICAgICAgc3lzLmV4aXQoMikKICAgICAgICBwYXJlbnRfaWQgPSBzeXMuYXJndlsyXQogICAgICAgIHRpdGxlID0gc3lzLmFyZ3ZbM10KICAgICAgICBjaGlsZHJlbiA9IGpzb24ubG9hZHMoc3lzLmFyZ3ZbNF0pIGlmIGxlbihzeXMuYXJndikgPiA0IGVsc2UgW10KICAgICAgICBwYXlsb2FkID0gewogICAgICAgICAgICAicGFyZW50IjogeyJ0eXBlIjogInBhZ2VfaWQiLCAicGFnZV9pZCI6IHBhcmVudF9pZH0sCiAgICAgICAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICAgICAgICAgInRpdGxlIjogewogICAgICAgICAgICAgICAgICAgICJ0aXRsZSI6IFsKICAgICAgICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAgICAgICAgInR5cGUiOiAidGV4dCIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAidGV4dCI6IHsiY29udGVudCI6IHRpdGxlfQogICAgICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICAgICAgXQogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9LAogICAgICAgICAgICAiY2hpbGRyZW4iOiBjaGlsZHJlbiwKICAgICAgICB9CiAgICAgICAgcmVxdWVzdCgiUE9TVCIsICIvcGFnZXMiLCBwYXlsb2FkPXBheWxvYWQpCiAgICAgICAgcmV0dXJuCgogICAgcHJpbnQoZiJVbmtub3duIGNvbW1hbmQ6IHtjbWR9IiwgZmlsZT1zeXMuc3RkZXJyKQogICAgc3lzLmV4aXQoMikKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgbWFpbigpCg=="

chmod +x "$SKILL_DIR/scripts/notion_api.py" || true
chmod +x "$SKILL_DIR/install.sh" || true

echo "Skill files installed."
echo ""

if [[ -f "$ENV_FILE" ]]; then
  echo "Existing Notion credentials found at:"
  echo "  $ENV_FILE"
  read -r -p "Replace them now? [y/N] " overwrite
  case "$overwrite" in
    y|Y|yes|YES)
      ;;
    *)
      echo "Keeping existing credentials."
      echo "Running verification..."
      python3 "$SKILL_DIR/scripts/notion_api.py" me
      echo ""
      echo "Notion is ready."
      echo "Skill location: $SKILL_DIR"
      echo "Credentials location: $ENV_FILE"
      if [[ -f "$SKILL_DIR/page_ids.txt" ]]; then
        echo "Page IDs location: $SKILL_DIR/page_ids.txt"
      fi
      echo ""
      echo "--------------------------------------------------"
      echo "Installation complete."
      echo ""
      echo "Now tell your OpenClaw agent about this setup with the prompt below:"
      echo "--------------------------------------------------"
      cat <<PROMPT
Notion is configured in this workspace.

Use the Notion skill at:
$SKILL_DIR

Credentials are stored at:
$ENV_FILE

When I ask you to read from or write to Notion, use this skill and its helper script.

Main helper script:
$SKILL_DIR/scripts/notion_api.py
PROMPT
      exit 0
      ;;
  esac
fi

read -r -p "Paste your Notion secret key: " notion_key

if [[ -z "$notion_key" ]]; then
  echo "No key entered. Aborting."
  exit 1
fi


cat > "$ENV_FILE" <<EOF
NOTION_API_KEY=$notion_key
EOF
chmod 600 "$ENV_FILE"

rm -f "$SKILL_DIR/page_ids.txt"

echo ""
echo "Saved credentials to $ENV_FILE"
echo "Verifying access..."
python3 "$SKILL_DIR/scripts/notion_api.py" me

echo ""
echo "Notion Workspace skill installed successfully."
echo "Skill location: $SKILL_DIR"
echo "Credentials location: $ENV_FILE"
echo ""
echo "--------------------------------------------------"
echo "Installation complete."
echo ""
echo "Now tell your OpenClaw agent about this setup with the prompt below:"
echo "--------------------------------------------------"
cat <<PROMPT
Notion is configured in this workspace.

Use the Notion skill at:
$SKILL_DIR

Credentials are stored at:
$ENV_FILE

When I ask you to read from or write to Notion, use this skill and its helper script.

Main helper script:
$SKILL_DIR/scripts/notion_api.py
PROMPT
